version: 2
jobs:
  build:
    docker:
      - image: bash:latest
    steps:
      - checkout
      - run: echo "build job"
  test:
    docker:
      - image: bash:latest
    steps:
      - checkout
      - run: echo "test job"
workflows:
  version: 2
  all_check:
    jobs:
      - test
      - build
